volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  indexer:
    image: night-bridge-indexer:latest
    ports:
      - 1234:1234
    env_file:        
      - .env
